### ISSUE TITLE
Problem with search after bulk import

### ISSUE THREAD

**Issue by Astro-Otter-Space** [kuzzleio/sdk-php#92]
I have imported my data into back-office from a bulk import in Postman.

Here's an exemple of document (in JSON format):
```
{
  "type": "Feature",
  "messier_id": "M1",
  "messier_order": 1,
  "properties": {
    "name": "M1",
    "desig": "NGC 1952",
    "alt": "Crab Nebula",
    "alt_fr": "Nébuleuse du crabe",
    "type": "snr",
    "type_label": "Supernova Remnant",
    "mag": 8.4,
    "const_id": "TAU",
    "dim": "6x4",
    "cl": ""
  },
  "geometry": {
    "type": "Point",
    "coordinates": [
      83.625,
      22.0167
    ]
  }
}
```
All my documents created with bul aven't got "meta" property. So, with kuzzle-php-sdk, when i make a search(), i have this error : 
```
ContextErrorExceptionNotice: Undefined index: _meta
--
in Collection.php (line 70)
```
![image](https://user-images.githubusercontent.com/7487421/39440050-f6bb8cae-4ca9-11e8-9efd-89400e97e4e8.png)

**Comment by Aschen** [comment]
Documents created with the Bulk Import route doesn't have Kuzzle metadata.  
It's a known bug and it will be fixed with [kuzzleio/kuzzle#1105](https://github.com/kuzzleio/kuzzle/pull/1105).  

~~However, Kuzzle can handle external collection (collection that are created directly in Elasticsearch) so the metadata could be absent in documents.  We will fix the SDK to handle this case.~~

Now metadata are always added to documents, even with the Bulk Import route (https://github.com/kuzzleio/kuzzle/pull/1105)

Thanks for the feedback!
